export default {
    permissions:{
        user:{
            management:"user.management",
            add:"add.user",
            del:"del.user",
            edit:"edit.user",
            list:"user.list",
            grantUserRole: "grant.user.role",
            grantUserPermission: "grant.user.permission"
        },
        role:{
            management: "role.management",
            add:"add.role",
            del:"del.role",
            edit:"edit.role",
            list:"role.list",
            grantRolePermission: "grant.role.permission"
        },
        permission:{
            management:"permission.management",
            add:"add.permission",
            del:"del.permission",
            edit:"edit.permission",
            list:"permission.list",
        },
        employee:{
            management: "employee.management",
            add:"add.employee",
            del:"del.employee",
            edit:"edit.employee",
            list:"employee.list",
            import:"import.employee"

        },
        farmer:{
            management:"farmer.management",
            add:"add.farmer",
            del:"del.farmer",
            edit:"edit.farmer",
            list:"farmer.list",
            import:"import.farmer"
        },
        member:{
            management:"member.management",
            add:"add.member",
            del:"del.member",
            edit:"edit.member",
            list:"member.list",
            import:"import.member"
        },
        cooperative:{
            management:"cooperative.management",
            add:"add.cooperative",
            del:"del.cooperative",
            edit:"edit.cooperative",
            list:"cooperative.list",
            import:"import.cooperative"
        },
        group:{
            management:"group.management",
            add:"add.group",
            del:"del.group",
            edit:"edit.group",
            list:"group.list"
        },
        materiel:{
            management:"materiel.management",
            add:"add.materiel",
            del:"del.materiel",
            edit:"edit.materiel",
            list:"materiel.list",
            import:"import.materiel"
        },
        plan:{
            management:"plan.management",
            add:"add.plan",
            del:"del.plan",
            edit:"edit.plan",
            list:"plan.list",
            import:"import.plan"
        },
        task:{
            management:"task.management",
            add:"add.task",
            del:"del.task",
            edit:"edit.task",
            list:"task.list",
            send:"send.task"
        },
        sop:{
            management:"sop.management",
            add:"add.sop",
            del:"del.sop",
            edit:"edit.sop",
            list:"sop.list"
        },
        orchard:{
            management:"orchard.management",
            add:"add.orchard",
            del:"del.orchard",
            edit:"edit.orchard",
            list:"orchard.list",
            import:"import.orchard.gpx"
        },
        codebook:{
            management:"codebook.management",
            add:"add.codebook",
            del:"del.codebook",
            edit:"edit.codebook",
            list:"codebook.list"
        },
        analysis:{
            management:"analysis.management"
        },
        app:{
            management:"app.version.management",
            add:"add.app.version",
            edit:"edit.app.version",
            list:"app.version.list"
        }

    }
}