server:
  port: 8888
spring:
  datasource:
    druid:
      develop:
        username: root
        password: G00dl^ck
#        password: Pwd123
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ican?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
        initialSize: 5
        minIdle: 5
        maxActive: 20
      release:
        username: root
        password: G00dl^ck
#        password: Pwd123
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ans?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
        initialSize: 5
        minIdle: 5
        maxActive: 20
mybatis-plus:
  # \u5982\u679C\u662F\u653E\u5728src/main/java\u76EE\u5F55\u4E0B
  # classpath:/com/ansimpleasy/agave/ans/mapper/xml/*Mapper.xml
  # \u5982\u679C\u662F\u653E\u5728resource\u76EE\u5F55 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath*:/com/ansimpleasy/agave/ans/mapper/**/*Mapper.xml
  #\u5B9E\u4F53\u626B\u63CF\uFF0C\u591A\u4E2Apackage\u7528\u9017\u53F7\u6216\u8005\u5206\u53F7\u5206\u9694
  type-aliases-package: com.ansimpleasy.agave.ans.entity.*
  global-config:
    #\u4E3B\u952E\u7C7B\u578B  0:"\u6570\u636E\u5E93ID\u81EA\u589E", 1:"\u7528\u6237\u8F93\u5165ID",2:"\u5168\u5C40\u552F\u4E00ID (\u6570\u5B57\u7C7B\u578B\u552F\u4E00ID)", 3:"\u5168\u5C40\u552F\u4E00ID UUID";
    id-type: 0
    #\u5B57\u6BB5\u7B56\u7565 0:"\u5FFD\u7565\u5224\u65AD",1:"\u975E NULL \u5224\u65AD"),2:"\u975E\u7A7A\u5224\u65AD"
    field-strategy: 2
    #\u9A7C\u5CF0\u4E0B\u5212\u7EBF\u8F6C\u6362
    db-column-underline: true
    #mp2.3+ \u5168\u5C40\u8868\u524D\u7F00 mp_
    #table-prefix: mp_
    #\u5237\u65B0mapper \u8C03\u8BD5\u795E\u5668
    refresh-mapper: true
    #\u6570\u636E\u5E93\u5927\u5199\u4E0B\u5212\u7EBF\u8F6C\u6362
    #capital-mode: true
    #\u903B\u8F91\u5220\u9664\u914D\u7F6E\uFF08\u4E0B\u97623\u4E2A\u914D\u7F6E\uFF09
    logic-delete-value: 4
    logic-not-delete-value: 0
  configuration:
    #\u914D\u7F6E\u8FD4\u56DE\u6570\u636E\u5E93(column\u4E0B\u5212\u7EBF\u547D\u540D&&\u8FD4\u56DEjava\u5B9E\u4F53\u662F\u9A7C\u5CF0\u547D\u540D)\uFF0C\u81EA\u52A8\u5339\u914D\u65E0\u9700as\uFF08\u6CA1\u5F00\u542F\u8FD9\u4E2A\uFF0CSQL\u9700\u8981\u5199as\uFF1A select user_id as userId\uFF09
    map-underscore-to-camel-case: true
    cache-enabled: false
    #\u914D\u7F6EJdbcTypeForNull, oracle\u6570\u636E\u5E93\u5FC5\u987B\u914D\u7F6E
    jdbc-type-for-null: 'null'